import { ObjectId } from "mongodb";
import mongoose from "mongoose";
export default class User {
  _id: number;
  username: string;
  email: string;
  password: string;
  image: string;

  constructor(
    username: string,
    email: string,
    password: string,
    image: string
  ) {
    this._id = 0; // generated by DB
    this.username = username;
    this.email = email;
    this.password = password;
    this.image = image;
  }
}

const userSchema = new mongoose.Schema({
  username: {
    type: String,
    unique: true,
    required: true,
  },
  email: {
    type: String,
    unique: true,
    required: true,
  },
  password: {
    type: String,
    required: true,
  },
  image: {
    type: String,
  },
});

export type UserMongo = {
  _id?: ObjectId;
  username: string;
  email: string;
  password: string;
  image: string;
};

export type mongooseResult = {
  $___proto__: {};
  $isNew: boolean;
  _doc: {
    UserMongo: UserMongo;
    __v: number;
  };
};
export const userModel = mongoose.model("users", userSchema, "users");
