export default class User {
  id : number
  username : string
  email : string
  password : string
  image : string

  constructor(username : string, email : string, password : string, image : string){
    this.id = 0   // generated by DB
    this.username = username
    this.email = email
    this.password = password
    this.image = image
  }
}